version: "3"

services:
  gatsby:
    build: ./gatsby/
    image: petitloan/personal_website_gatsby:latest
    container_name: personal_website_gatsby
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
