version: "3.7"

services:
  ghost:
    image: ghost:3.13.3-alpine
    depends_on:
      - db
    secrets:
      - MYSQL_PASSWORD
    environment:
      url: https://www.loanpetit.com:2368
      database__client: mysql
      database__connection__host: db
      database__connection__database: ghost
      database__connection__user: ghost
      database__connection__password_FILE: /run/secrets/MYSQL_PASSWORD
    volumes:
      - "ghost_media_storage:/var/lib/ghost/content"
    configs:
      - source: entrypoint
        target: /usr/local/bin/docker-entrypoint.sh
        uid: "1000"
        gid: "1000"
        mode: 0510
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.ghost.loadbalancer.server.port=2368"
        - "traefik.http.routers.ghost.rule=HostRegexp(`{host:(?:www.)?loanpetit.com}`)"
        - "traefik.http.routers.ghost.entrypoints=ghost"
        - "traefik.http.routers.ghost.tls.certresolver=default"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  db:
    image: mariadb
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_USER: ghost
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
    volumes:
      - "db_data:/var/lib/mysql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

configs:
  entrypoint:
    file: ./ghost_entrypoint.sh

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_PASSWORD:
    external: true

volumes:
  db_data:
  ghost_media_storage:
