version: "3.7"

services:
  traefik:
    image: "traefik:v2.2"
    command:
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.ghost.address=:2368"
      - "--entrypoints.traefik.address=:8080"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.default.acme.email=petit.loan1@gmail.com"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "2368:2368"
      - "8080:8080"
    secrets:
      - TRAEFIK_USERS
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Redirect HTTP to HTTPS
        - "traefik.http.middlewares.httpsredirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.httpsredirect.redirectscheme.permanent=true"
        - "traefik.http.routers.httpsredirect.rule=HostRegexp(`{host:.*\\.?loanpetit.com}`)"
        - "traefik.http.routers.httpsredirect.entrypoints=web"
        - "traefik.http.routers.httpsredirect.middlewares=httpsredirect"
        # Expose secured dashboard
        - "traefik.http.routers.api.rule=HostRegexp(`{host:(?:www\\.)?loanpetit.com}`)"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.entrypoints=traefik"
        - "traefik.http.routers.api.tls.certresolver=default"
        - "traefik.http.routers.api.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.usersfile=/run/secrets/TRAEFIK_USERS"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"

secrets:
  TRAEFIK_USERS:
    external: true

volumes:
  letsencrypt: