version: '3'

services:
  ghost:
    image: ghost:alpine
    container_name: personal_website_ghost
    depends_on:
      - db
    env_file:
      - ./ghost.env
    ports:
      - "8080:2368"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  db:
    image: mysql:5.7
    container_name: personal_website_db
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
        - "db-data:/var/lib/mysql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  db-data:
