name: Deployment pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images to Docker Hub
        run: ./build_and_push_images.sh
        working-directory: ./swarm/

      - name: Load AWS EC2 private key
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.aws_ec2_key.pem
          chmod 600 ~/.aws_ec2_key.pem

      - name: Create SSH tunnel to remote EC2 Docker socket
        run: ssh -o StrictHostKeyChecking=no -i ~/.aws_ec2_key.pem -fNL localhost:2376:/var/run/docker.sock ${{ secrets.AWS_EC2_DESTINATION }}

      - name: Deploy services to the remote swarm.
        run: docker -H localhost:2376 stack deploy --with-registry-auth $(for f in docker-compose.*.yml; do echo -n "-c $f "; done) mysite
        working-directory: ./swarm/

      - name: Remove all unused containers, networks and images (both dangling and unreferenced).
        run: docker -H localhost:2376 system prune -af
